apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    application: scaler
  name: controller:scaler
rules:
- apiGroups:
  - arjunnaik.in
  resources:
  - scalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - '*/scale'
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - controllerrevisions
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - arjunnaik.in
  resources:
  - scalers/status
  verbs:
  - get
  - patch
  - update

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-sa
  namespace: kube-system
  labels:
    application: scaler

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller:scaler
  labels:
    application: scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: controller:scaler
subjects:
- kind: ServiceAccount
  name: scaler-sa
  namespace: kube-system